### PR TITLE
Fix the broken links to 2 widgets.

### PR DESCRIPTION
**Pull request by roemhildtg**
I had moved them prior to this and forgot to update their links here.

### CODE REVIEW

**Comment by tmcgee** [comment]
Thanks! Do you want to add the two new ones: `Heatmap` and `MetadataDialog`?

**Comment by roemhildtg** [comment]
I will eventually, I am planning on writing up some docs when I get to it.

**Comment by tmcgee** [comment]
OK. That works.

After merge, I noticed that this link does not work: https://github.com/roemhildtg/CMV_Widgets/tree/master/RelatedRecordTable_Widget

Did you mean this one: https://github.com/roemhildtg/CMV_Widgets/tree/master/widgets/RelationshipTable ??

**Comment by roemhildtg** [comment]
Yes, I changed both of those links. They should both be working now.

**Comment by tmcgee** [comment]
After merging, I would get the first page (with a 404 error) every other time I clicked on the link from the read-me. Must have been a caching thing - either at github or local. All better now.

**Comment by roemhildtg** [comment]
I was just thinking it could be cached from before. It is odd that it went
back and forth a bit.

**Pull request merged**
